repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: no-commit-to-branch
      - id: name-tests-test
        args: ['--django']
      - id: check-yaml
      - id: debug-statements
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: linting
        name: Run linting suite consisting of (flake8, isort, mypy, black)
        language: system
        entry: make local-lint
        pass_filenames: false
