.only:version-tags:
  only:
    refs:
      - tags@meltano/meltano-permissions
    variables:
      - $CI_COMMIT_TAG =~ /^v*/

.only:master:
  only:
    refs:
      - master@meltano/meltano-permissions
