publish:
  extends: .only:version-tags
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    entrypoint: [""]
  stage: publish
  before_script:
    - pip install twine
  script:
    - twine upload /permifrost/dist/*
