.test:
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    entrypoint: [""]
  before_script:
    - pip install '.[dev]'

lint:
  extends: .test
  before_script:
    - pip install black
  script:
    - make local-show-lint

pytest:
  extends: .test
  script:
    - pytest -v --cov-report= --cov permifrost -m "$PYTEST_MARKERS"
    - coverage combine .coverage
    - coverage report
    - coverage html
  artifacts:
    paths:
      - htmlcov/
    when: on_success
